### ISSUE TITLE
Stop vendoring in RevealJS

### ISSUE THREAD

**Issue by RealOrangeOne** [Adimote/sourcebots-dev-presentations#1]
Rather than vendoring in RevealJS, could we not just use a CDN? Or if we really _have to_ vendor it in, just vendor in the dist files, rather than a snapshot of the whole repo. Option 3 would just be to submodule it, but I don't know if GitHub checks those out when it builds it.

**Comment by Adimote** [comment]
GitHub does automatically load in the submodules :+1:, I've added a submodule in 208013a84242c219040b7836994984db1099932d
